# Generated by Django 4.2.7 on 2024-02-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolistapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(verbose_name=100),
        ),
    ]
