# Generated by Django 4.2.7 on 2024-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolistapp", "0002_alter_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="title",
            field=models.CharField(default="Default Title", max_length=255),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(),
        ),
    ]
